exp_name: test
seed: 1
torch_deterministic: True
cuda: True
track: False
wandb_project_name: rl-radiotherapy
use_wandb: False
use_tensorboard: True

total_timesteps:  5000000
save_timesteps: 500000
save_model: True
learning_rate: 3e-4
num_envs: 16
num_steps: 100
anneal_lr: True
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 32
update_epochs: 10
norm_adv: True
clip_coef: 0.1
clip_vloss: True
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: None

visionless: True

batch_size: 0
minibatch_size: 0
num_iterations: 0
output_dir: ""